### PR TITLE
Pull Request for Rocket Structure

### PR DESCRIPTION
**Pull request by chuaindia**
In this branch followings are done :

- Create a route and a view component. 
- Used <NavLink /> for the page navigation links and style active class to indicate which section/page.
- Underline the navigation page.
- Created a directory for all Redux state slice files.
- The Structure of the Rocket page is incorporated.
- The data corresponding to Rockets are fetched from the corresponding API, mentioned in the project.

### CODE REVIEW

**Review by Harrynoqs — CHANGES_REQUESTED** [review]
Hi @chuaindia 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
Highlights

:white_check_mark: You used Gitflow correctly
:white_check_mark: Linter checks passed
:white_check_mark: Your app works 

Required Changes :recycle: 

Check the comments under the review.
:ballot_box_with_check:  Kindly a proper description of this phase of the milestone. e.g Added fetch rockets and fetch data

**Comment by chuaindia** [comment]
@Harrynoqs :+1: 

Thank you for your valuable opinion.

This branch is showing the following features distinctively: 

- The Structure of the Rocket page is incorporated.
- The data corresponding to Rockets are fetched from the corresponding API, mentioned in the project.

**Comment by chuaindia** [comment]
A screenshot of the Rocket page shows the structure is attached :

Screenshot (110)

**Review by Harrynoqs — APPROVED** [review]
Hi @chuaindia 
Status: Approved :heavy_check_mark:

Your project is complete! There is nothing else to say other than... it's time to merge it ship
Congratulations! :tada:

Cheers and Happy coding! :clap:  :clap: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
